version: '3.8'

services:

  postgres:
      restart: always
      image: postgis/postgis
      container_name: pgsql
      environment:
        - POSTGRES_DB=ai
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
      ports:
        - '5434:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        
  redis:
    image: redis
    container_name: redis
    ports:
     - "6379:6379"

  app:
    build: .
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    container_name: worker
    command: celery -A aiproject worker --loglevel=INFO
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
      - postgres


  worker-dashboard:
    build: .
    container_name: flower
    command:  celery -A aiproject --broker=redis://redis:6379//  flower --address=0.0.0.0 --port=5000
    ports:
      - 5500:5000
    depends_on:
      - app
      - redis
      - worker