name: Backend Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      ubuntu-latest
    services:
      postgres: # we need a postgres docker image to be booted a side car service to run the tests that needs a db
        image: postgres:12
        env: # the environment variable must match with app/settings.py if block of DATBASES variable otherwise test will fail due to connectivity issue.
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ai
        ports:
          - 5432:5432 # exposing 5432 port for application to use
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Postgis for Psql 
        run: |
          sudo apt-get update
          sudo apt install postgis postgresql-postgis
      - name : Install GDAL and psycopg2
        run : |
          sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
          sudo apt-get install gdal-bin
          sudo apt-get install libgdal-dev
          sudo apt-get install python3-psycopg2
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal      
      - name : Check gdal version
        run : |
          ogrinfo --version
      - name : Install gdal python
        run : |
          pip install gdal==3.3.2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend/
          pip install -r requirements.txt
      - name: Test Build
        run: |
          cd backend/
          python manage.py makemigrations
          python manage.py migrate